<?php

declare(strict_types=1);

namespace Atoms\Cli\Cloudflare;

/**
 * Reads and writes the `ATOMS_SHARED_SECRET` line of a Worker project's
 * `.dev.vars` — the file `wrangler dev` loads into the Worker's environment on
 * its own (docs/shared-secret.md). Shared between {@see \Atoms\Cli\Command\DevCommand},
 * which guarantees the line exists, and {@see \Atoms\Cli\Command\TokenCommand},
 * which reads it as one of the bearer-derivation sources.
 */
final class DevVars
{
    public const FILE = '.dev.vars';

    public const SECRET_KEY = 'ATOMS_SHARED_SECRET';

    public static function path(string $workerDir): string
    {
        return rtrim($workerDir, '/') . '/' . self::FILE;
    }

    /**
     * The value of ATOMS_SHARED_SECRET in $workerDir/.dev.vars, or null when
     * the file does not exist or carries no such line.
     */
    public static function readSecret(string $workerDir): ?string
    {
        $contents = @file_get_contents(self::path($workerDir));

        return \is_string($contents) ? self::extractSecret($contents) : null;
    }

    /**
     * Append a freshly generated ATOMS_SHARED_SECRET line to $workerDir/.dev.vars,
     * creating the file with mode 0600 when it does not yet exist. The caller
     * is responsible for checking {@see self::readSecret()} first — this
     * always generates and appends a new line.
     *
     * @return string the generated secret, base64-encoded
     */
    public static function appendGeneratedSecret(string $workerDir): string
    {
        $path = self::path($workerDir);
        $value = base64_encode(random_bytes(32));
        $isNew = !is_file($path);

        $block = ($isNew ? '' : "\n")
            . "# Per-machine dev secret, generated by atoms dev. Never commit this file;\n"
            . "# the app side's .env needs the identical " . self::SECRET_KEY . " value.\n"
            . self::SECRET_KEY . '=' . $value . "\n";

        file_put_contents($path, $block, \FILE_APPEND | \LOCK_EX);

        if ($isNew) {
            chmod($path, 0600);
        }

        return $value;
    }

    private static function extractSecret(string $contents): ?string
    {
        if (preg_match('/^[ \t]*' . preg_quote(self::SECRET_KEY, '/') . '[ \t]*=[ \t]*(.*)$/m', $contents, $m) !== 1) {
            return null;
        }

        $value = trim(rtrim($m[1], "\r"));
        if (\strlen($value) >= 2) {
            $quote = $value[0];
            if (($quote === '"' || $quote === "'") && str_ends_with($value, $quote)) {
                $value = substr($value, 1, -1);
            }
        }

        return $value === '' ? null : $value;
    }
}
