<?php

declare(strict_types=1);

namespace Atoms\Cli\Cloudflare;

use Atoms\Cli\Config\EnvFile;

/**
 * Reads and writes the `ATOMS_SHARED_SECRET` line of a Worker project's
 * `.dev.vars` — the file `wrangler dev` loads into the Worker's environment on
 * its own (docs/shared-secret.md). Shared between {@see \Atoms\Cli\Command\DevCommand},
 * which guarantees the line exists, and {@see \Atoms\Cli\Command\TokenCommand},
 * which reads it as one of the bearer-derivation sources.
 *
 * Parsed by {@see EnvFile}, the same reader the app's `.env` uses — `atoms
 * dev` copies this value there.
 */
final class DevVars
{
    public const FILE = '.dev.vars';

    public const SECRET_KEY = 'ATOMS_SHARED_SECRET';

    public static function path(string $workerDir): string
    {
        return rtrim($workerDir, '/') . '/' . self::FILE;
    }

    /**
     * The value of ATOMS_SHARED_SECRET in $workerDir/.dev.vars, or null when
     * the file does not exist or carries no such line.
     */
    public static function readSecret(string $workerDir): ?string
    {
        return EnvFile::read(self::path($workerDir), self::SECRET_KEY);
    }

    /** A fresh 32-byte secret, base64-encoded. */
    public static function generate(): string
    {
        return base64_encode(random_bytes(32));
    }

    /**
     * Write $value as the ATOMS_SHARED_SECRET, creating the file at mode 0600
     * if needed. The file is a generated projection of the app's `.env`, so an
     * existing value is replaced rather than preserved.
     */
    public static function writeSecret(string $workerDir, string $value): void
    {
        EnvFile::write(
            self::path($workerDir),
            self::SECRET_KEY,
            $value,
            'Generated by atoms dev from the app\'s .env — edits are overwritten.',
            'Never commit this file.',
        );
    }
}
